### ISSUE TITLE
[BUG] Joined Pools Not Displayed in Pools Table

### ISSUE THREAD

**Issue by devpavan04** [tangle-network/dapp#2620] opened 2024-10-29 14:36 UTC
### Overview

After successfully selecting and depositing into a pool, the newly staked (joined) pool does not appear in the `My Pools` table.

- [ ] Users should be able to immediately see their joined pools in the table after staking to confirm their participation.

### Join a Pool

https://github.com/user-attachments/assets/6d566cbd-1173-4259-8566-5a61c4e1ae86

### My Pools

![CleanShot 2024-10-29 at 07 31 28](https://github.com/user-attachments/assets/07b3664c-db5a-42ce-b510-5ccf1ebe2797)

**Comment by yurixander** [comment] 2024-11-26 00:39
Duplicate of #2618

**Closed by yurixander** 2024-11-26 00:39 UTC
Labels: bug 🪲
